apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-service
  labels:
    app: hello-kubernetes
spec:
  type: NodePort
  selector:
    app: hello-kubernetes
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 3000       
      nodePort: 30007        
